FROM nvidia/cuda:10.0-cudnn7-runtime-ubuntu18.04
WORKDIR /tmp
COPY requirements.txt .
RUN apt-get update -y 
RUN apt-get install -y python3 python3-pip
RUN pip3 install --upgrade pip
RUN pip3 install -r requirements.txt
